name: red_rocket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^7.8.4
  flutter_bloc: ^9.1.1
  dio: ^5.4.1
  retrofit: ^4.1.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_screenutil: ^5.9.0
  equatable: ^2.0.5
  mockito: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.1.0
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true